FROM golang:1.18-alpine as build_producer

ENV CGO_ENABLED 0
COPY . /service

WORKDIR /service
RUN go mod download

WORKDIR /service/app/services/producer
RUN go build

# One could use a thinner image but here one can ssh into the container
FROM alpine:3.17

COPY --from=build_producer /service/app/services/producer/producer /service/
WORKDIR /service


CMD ["./producer"]