name: Makefile CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - name: "Checking out the repo"
      uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "Build the image"
      run: |
        docker build \
        --file dockerfile.producer \ 
        --tag ${{ env.IMAGE_TAG }} .
