name: Makefile CI

on:
  workflow_dispatch
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VERSION: 4.0.0
jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - name: "Checking out the repo"
      uses: actions/checkout@v3
    - name : "Debug Variables"
      run: |
        echo "${{ env.REGISTRY }}"
        echo "${{ github.repository_owner }}"
        echo "${{ secrets.GITHUB_TOKEN }}"
        echo "$IMAGE_NAME"
    - uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "Cat config"
      run: cat ~/.docker/config.json
    #- name: "auth"
    #  run: cat ~/.docker/config.json | jq -r ' .auths."ghcr.io".auth' | base64 -d | rev
    # - name: "Build the image"
    #  run: docker buildx build . --file dockerfile.producer --tag $IMAGE_NAME
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ghcr.io/test-packages-org/producer-golang:latest

