name: Makefile CI

on:
  workflow_dispatch
env:
  REGISTRY: ghcr.io
  VERSION: "1.0.0"
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - name: "Checking out the repo"
      uses: actions/checkout@v3
    - name : "Debug Variables"
      run: |
        echo "${{ env.REGISTRY }}"
        echo "${{ github.actor }}"
        echo "${{ secrets.GITHUB_TOKEN }}"
    - uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "Build the image"
      run: docker build . --file dockerfile.producer --tag $IMAGE_NAME
    - name: "Push the image"
      run: |
          IMAGE_ID=$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

