name: Makefile CI

on:
  workflow_dispatch
env:
  REGISTRY: ghcr.io
  VERSION: latest
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - name: "Checking out the repo"
      uses: actions/checkout@v3
    - name : "Debug Variables"
      run: |
        echo "${{ env.REGISTRY }}"
        echo "${{ github.repository_owner }}"
        echo "${{ secrets.GITHUB_TOKEN }}"
        echo "$IMAGE_NAME"
    - uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "Build the image"
      run: docker build . --file dockerfile.producer --tag $IMAGE_NAME
    - name: "Push the image"
      run: |
          IMAGE_ID=$REGISTRY/$IMAGE_NAME
          echo $IMAGE_ID
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID

