name: Makefile CI

on:
  workflow_dispatch
env:
  REGISTRY: ghcr.io
  IMAGE_TAG: "1.0.0"
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - name: "Checking out the repo"
      uses: actions/checkout@v3
    - name : "Debug Variables"
      run: |
        echo "${{ env.REGISTRY }}"
        echo "${{ github.actor }}"
        echo "${{ secrets.GITHUB_TOKEN }}"
    - uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "Build the image"
      run: docker build . --file dockerfile.producer --tag producer-golang:${{ env.IMAGE_TAG }}
    - name: "Push the image"
      run: docker push ghcr.io/producer-golang:${{ env.IMAGE_TAG }}
